dwh:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/opt/airflow/db_files/dwh.duckdb'
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "eu-central-1"
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
       